apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-api-order
  template:
    metadata:
      labels:
        app: enowshop-api-order
    spec:
      containers:
        - name: enowshop-api-order
          image: gcr.io/enowhop/enowshop-api-orders:17
          ports:
              - containerPort: 8081
          env:
            - name: A-POSTGRES_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: A-POSTGRES_DATABASE_URL
            - name: MONGO_DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: MONGO_DATABASE_DB
            - name: MONGO_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: MONGO_DATABASE_HOST
            - name: MONGO_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: MONGO_DATABASE_PORT
            - name: MONGO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: MONGO_DATABASE_USER
            - name: MONGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: MONGO_DATABASE_PASSWORD
            - name: MONGO_DATABASE_AUTH_SOURCE
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: MONGO_DATABASE_AUTH_SOURCE
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: KEYCLOAK_PUBLIC_KEY
            - name: PUBNUB_PUBLISH_KEY
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: PUBNUB_PUBLISH_KEY
            - name: PUBNUB_SUBSCRIBE_KEY
              valueFrom:
                secretKeyRef:
                  name: api-orders-secrets
                  key: PUBNUB_SUBSCRIBE_KEY